server:
  port: 9000
  
spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      routes:
        - id: book_service
          uri:  http://localhost:9001
          predicates:
            - Path=/api/v1/books/**
        - id: employee_service
          uri:  http://localhost:9002
          predicates:
            - Path=/api/v1/employees/**
      default-filters:
        - DedupeResponseHeader=Access-Controler-Allow-Credentials Access-Controler-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:  "*"
            allowedMethods:  "*"
            allowedHeaders:  "*"